### ISSUE TITLE
AppImage fails to see headphones by USB (resolved)

### ISSUE THREAD

**Issue by stylerw** [george-norton/headphones-toolbox#3]
Mostly leaving a note here for future users of the AppImage, or potentially for the Dev to warn folks. I'm using Fedora 38, on a Framework Laptop (although I don't think the hardware matters here).

The .AppImage opens fine, but the program doesn't recognize the headphones when plugged in when run normally. This isn't entirely shocking, though, as AppImage seldom plays well with raw USB access due to security policies.

Although there's a fine-grained and system-specific solution to this involving changing the security configuration of USB access for appimage, a quick and less-secure solution is to instead:

```
cd folder_containing_appimage
sudo ./ploopy-headphones-toolbox_0.0.1_amd64.AppImage
```

At this point, it will have all the access in the world, for better or worse, and will absolutely be able to see and modify the headphone settings.

Thanks so much for supporting Linux at all with the AppImage compilation, and for making this software.

**Comment by george-norton** [comment]
Have you added the udev rule from the quickstart guide?

https://github.com/george-norton/headphones-toolbox#quickstart-guide

**Comment by stylerw** [comment]
I did, but that particular command didn't work on my system (perhaps due to SELinux?).  Hence posting an alternate, albeit bad, solution.
