### ISSUE TITLE
Plot description overlay misaligned beyond a certain window width

### ISSUE THREAD

**Issue by unfa** [george-norton/headphones-toolbox#8]
If I make the Toolbox window too wide, the descriptive spectrum overlay ("bass", "mids", "presence" etc.) stays at a fixed width and becomes misaligned.

![image](https://github.com/george-norton/headphones-toolbox/assets/491704/f7959600-5bc2-477c-8592-8b935546786f)

**Comment by george-norton** [comment]
Thanks, the labels are a actually a background image rather than part of the graph, I guess once the aspect ratio changes too much things go a bit off.

**Comment by Igigog** [comment]
Good catch! I'll try to do something with it tomorrow.
